#!/bin/bash
#dotnet msbuild -t:restore,build -p:Configuration=Release;RestorePackagesConfig=true

# https://stackoverflow.com/a/246128
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
dotnetp="dotnet publish -c Release"

dist=$SCRIPT_DIR/dist
rm -rf $dist
mkdir -p $dist

dirs=('Client' 'Server' 'Shared')
for dir in "${dirs[@]}"; do
    cd $SCRIPT_DIR/$dir
    $dotnetp
    mkdir -p $dist/$dir
    cp -r ./bin/Release/*/publish/*.dll ../dist/$dir
    rm -fr ./bin ./obj
    cd ..
done

echo "[Realifev-CSharp-Template]" >$dist/config.ini
for dir in "${dirs[@]::${#dirs[@]}-1}"; do
    cp -r $dist/Shared/* $dist/$dir
done
cp $SCRIPT_DIR/fxmanifest.lua $dist

rm -rf $dist/Shared $dist/*/CitizenFX.Core.*.dll
